### ISSUE TITLE
Coupon Prediction - Starting out.. 

### ISSUE THREAD

**Issue by SudalaiRajkumar** [daxiongshu/Coupon-Purchase-Prediction#1]
Hi Carl,

We can use this issue tracker similar to our email or Kaggle forums. Whenever we post something here, it will also send a mail to us. It is easy to copy paste the codes here and also to attach the pictures. 

I have committed the codes for our best submission into the github under the folder SRK/sub10/.

Readme file has the order of codes to run. I will write more about the methodology here shortly. 

Thanks,

**Comment by daxiongshu** [comment]
Hi, I got the email, thanks!

**Comment by daxiongshu** [comment]
Yeah, it is great. Let's do it this way : )

**Comment by SudalaiRajkumar** [comment]
Great :) I will add the methodology here shortly.

**Comment by daxiongshu** [comment]
Hi, I have a very naive question. In splitCoupon.py, why is the model start date is 2012.6.17 ? I didn't find it in the data page. Thank you. 
Another question, I didn't find the config.py file. Is it required to reproduce the sub10.csv?
thank you

**Comment by SudalaiRajkumar** [comment]
Nice catch Carl. I have added the config.py file in github.

I thought of using the last weeks training data as validation data and so wanted to split the data before 2012-06-17 as dev data and last week as val data. This model start date variable is the date used for that splitting. Maybe the variable name is confusing. Am sorry about that.

**Comment by SudalaiRajkumar** [comment]
Carl. Are we not able to reproduce submission 10?! I see a different score when you tried to reproduce

**Comment by daxiongshu** [comment]
Hi, I am not sure if I have done it correctly. or it is just a matter of random seed. You could also rerun it. It should not take long.

**Comment by SudalaiRajkumar** [comment]
yes. I will also run it once and try.

Can we have a quick skype call if you are free?

**Comment by SudalaiRajkumar** [comment]
Carl, I tried to reproduce the submission and I am able to reproduce it correctly. 

My version of the python modules are as follows:
pandas - 0.16.2
xgboost - 0.3 

I am also using a random seed for sampling and so it should not affect the sampling as well. I am not sure what went wrong here :(

I am attaching the head of some of my intermediate files for your reference

```
$ head -10 train_idvs.csv 
USER_ID_hash,COUPON_ID_hash,UserGender,UserAge,UserPrefName,UserDaysSinceRegistered,UserWithdrawn,NoOfPurchases,DaysSinceLastPurchase,NoOfPurchasesLastweek,NoOfPurchasesLast15Days,NoOfPurchasesLast30Days,NoOfPurchasesLast60Days,NoOfPurchasesLast90Days,CouponCapsuleText,CouponGenreName,CouponPriceRate,CouponCatalogPrice,CouponDiscountPrice,CouponDispPeriod,CouponValidPeriod,CouponUsableMon,CouponUsableTue,CouponUsableWed,CouponUsableThu,CouponUsableFri,CouponUsableSat,CouponUsableSun,CouponUsableHol,CouponUsableBeforeHol,CouponLargeAreaName,CouponKenName,CouponSmallAreaName,CapsuleTextCount,CapsuleTextCountNorm,GenreNameCount,GenreNameCountNorm,LargeAreaNameCount,LargeAreaNameCountNorm,SmallAreaNameCount,SmallAreaNameCountNorm,KenNameCount,KenNameCountNorm,PriceRateMin,PriceRateMax,PriceRateMean,PriceRateBetMeanMax,PriceRateBetMinMean,PriceRateGrtMax,PriceRateLessMin,CatalogPriceMin,CatalogPriceMax,CatalogPriceMean,CatalogPriceBetMeanMax,CatalogPriceBetMinMean,CatalogPriceGrtMax,CatalogPriceLessMin,DiscountPriceMin,DiscountPriceMax,DiscountPriceMean,DiscountPriceBetMeanMax,DiscountPriceBetMinMean,DiscountPriceGrtMax,DiscountPriceLessMin,DispPeriodMin,DispPeriodMax,DispPeriodMean,DispPeriodBetMeanMax,DispPeriodBetMinMean,DispPeriodGrtMax,DispPeriodLessMin,MondayCount,MondayCountNorm,TuesdayCount,TuesdayCountNorm,WednesdayCount,WednesdayCountNorm,ThursdayCount,ThursdayCountNorm,FridayCount,FridayCountNorm,SaturdayCount,SaturdayCountNorm,SundayCount,SundayCountNorm,HolidayCount,HolidayCountNorm,BeforeHolidayCount,BeforeHolidayCountNorm,DV
17f0f6675b8a3f2d9b2f2035cf9b6c57,9d5d4fd3b9a279c65dcc0ae35db89950,1,41.0,千葉県,179,0,0,9999,0,0,0,0,0,宅配,宅配,50,2000,999,2,,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,北海道,北海道,北海道,0,0,0,0,0,0,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
17f0f6675b8a3f2d9b2f2035cf9b6c57,93b0927ffeb3822bd0ae458dbc15df17,1,41.0,千葉県,179,0,0,9999,0,0,0,0,0,宅配,宅配,50,3545,1772,2,,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,北海道,北海道,北海道,0,0,0,0,0,0,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,55d73389cb611ac48d6c878258ab73a5,1,41.0,千葉県,179,0,0,9999,0,0,0,0,0,グルメ,グルメ,50,6000,2980,2,91.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,関東,神奈川県,横浜,0,0,0,0,0,0,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,d61754cde46e28f1eaf8e7c09c8ab9e1,1,41.0,千葉県,179,0,0,9999,0,0,0,0,0,グルメ,グルメ,50,8500,4200,5,89.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,九州・沖縄,福岡県,福岡,0,0,0,0,0,0,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,27383a956311bf6ae1bc885fc87233b1,1,41.0,千葉県,179,0,0,9999,0,0,0,0,0,グルメ,グルメ,55,3340,1480,0,179.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,関西,大阪府,キタ,0,0,0,0,0,0,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,-999,-999,-999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,a262c7ff56a5cd3de3c5c40443f3018c,1,41.0,千葉県,251,0,1,302,0,0,0,0,0,その他,その他のクーポン,80,500,100,36,67.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,関東,東京都,新宿・高田馬場・中野・吉祥寺,0,0,0,0,0,0,0,0,0,0,50.0,50.0,50.0,0,0,1,0,2000.0,2000.0,2000.0,0,0,0,1,999.0,999.0,999.0,0,0,0,1,2.0,2.0,2.0,0,0,1,0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1
17f0f6675b8a3f2d9b2f2035cf9b6c57,fb5453a4e36b8c652e732c9269f022aa,1,41.0,千葉県,251,0,1,302,0,0,0,0,0,ヘアサロン,ヘアサロン,72,17850,4980,2,92.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,関東,東京都,池袋・神楽坂・赤羽,0,0,0,0,0,0,0,0,0,0,50.0,50.0,50.0,0,0,1,0,2000.0,2000.0,2000.0,0,0,1,0,999.0,999.0,999.0,0,0,1,0,2.0,2.0,2.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,e3ec0d2e2614cfc5360ad1ea68c580c4,1,41.0,千葉県,251,0,1,302,0,0,0,0,0,グルメ,グルメ,52,7350,3480,3,177.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,関東,神奈川県,横浜,0,0,0,0,0,0,0,0,0,0,50.0,50.0,50.0,0,0,1,0,2000.0,2000.0,2000.0,0,0,1,0,999.0,999.0,999.0,0,0,1,0,2.0,2.0,2.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,2659d9dfa56720f249ba629758fd12ad,1,41.0,千葉県,251,0,1,302,0,0,0,0,0,宅配,宅配,50,2564,1280,2,,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,関東,東京都,池袋・神楽坂・赤羽,1,1.0,1,1.0,0,0,0,0,0,0,50.0,50.0,50.0,1,0,0,0,2000.0,2000.0,2000.0,0,0,1,0,999.0,999.0,999.0,0,0,1,0,2.0,2.0,2.0,1,0,0,0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,1,1.0,0
```

```
$ head -10 test_idvs.csv 
USER_ID_hash,COUPON_ID_hash,UserGender,UserAge,UserPrefName,UserDaysSinceRegistered,UserWithdrawn,NoOfPurchases,DaysSinceLastPurchase,NoOfPurchasesLastweek,NoOfPurchasesLast15Days,NoOfPurchasesLast30Days,NoOfPurchasesLast60Days,NoOfPurchasesLast90Days,CouponCapsuleText,CouponGenreName,CouponPriceRate,CouponCatalogPrice,CouponDiscountPrice,CouponDispPeriod,CouponValidPeriod,CouponUsableMon,CouponUsableTue,CouponUsableWed,CouponUsableThu,CouponUsableFri,CouponUsableSat,CouponUsableSun,CouponUsableHol,CouponUsableBeforeHol,CouponLargeAreaName,CouponKenName,CouponSmallAreaName,CapsuleTextCount,CapsuleTextCountNorm,GenreNameCount,GenreNameCountNorm,LargeAreaNameCount,LargeAreaNameCountNorm,SmallAreaNameCount,SmallAreaNameCountNorm,KenNameCount,KenNameCountNorm,PriceRateMin,PriceRateMax,PriceRateMean,PriceRateBetMeanMax,PriceRateBetMinMean,PriceRateGrtMax,PriceRateLessMin,CatalogPriceMin,CatalogPriceMax,CatalogPriceMean,CatalogPriceBetMeanMax,CatalogPriceBetMinMean,CatalogPriceGrtMax,CatalogPriceLessMin,DiscountPriceMin,DiscountPriceMax,DiscountPriceMean,DiscountPriceBetMeanMax,DiscountPriceBetMinMean,DiscountPriceGrtMax,DiscountPriceLessMin,DispPeriodMin,DispPeriodMax,DispPeriodMean,DispPeriodBetMeanMax,DispPeriodBetMinMean,DispPeriodGrtMax,DispPeriodLessMin,MondayCount,MondayCountNorm,TuesdayCount,TuesdayCountNorm,WednesdayCount,WednesdayCountNorm,ThursdayCount,ThursdayCountNorm,FridayCount,FridayCountNorm,SaturdayCount,SaturdayCountNorm,SundayCount,SundayCountNorm,HolidayCount,HolidayCountNorm,BeforeHolidayCount,BeforeHolidayCountNorm,DV
17f0f6675b8a3f2d9b2f2035cf9b6c57,1442892055dac7335c115d50186bedd3,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,ホテル,ホテル・旅館,63,13174,4800,4,90,1,1,1,1,1,0,1,1,0,九州・沖縄,福岡県,福岡,0,0,0,0,0,0,0,0,0,0,50.0,100.0,77.5,0,1,0,0,1.0,2625.0,1281.5,0,0,1,0,0.0,999.0,406.0,0,0,1,0,2.0,36.0,12.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,e0e86297922c5799ee19881ca999b81d,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,グルメ,グルメ,50,4000,1980,5,114,1,1,1,1,1,1,0,1,1,関東,神奈川県,横浜,0,0,0,0,3,0.75,0,0,0,0,50.0,100.0,77.5,0,1,0,0,1.0,2625.0,1281.5,0,0,1,0,0.0,999.0,406.0,0,0,1,0,2.0,36.0,12.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,cb4c67c749dc53afd24aea31de705108,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,ホテル,ホテル・旅館,50,36000,18000,4,119,1,1,1,1,1,0,1,1,0,関西,和歌山県,和歌山,0,0,0,0,0,0,0,0,0,0,50.0,100.0,77.5,0,1,0,0,1.0,2625.0,1281.5,0,0,1,0,0.0,999.0,406.0,0,0,1,0,2.0,36.0,12.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,42cc500acba3c79883cfd40adcd5ae96,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,宅配,宅配,81,5410,980,3,NA,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,北海道,北海道,北海道,1,0.25,1,0.25,1,0.25,1,0.25,1,0.25,50.0,100.0,77.5,1,0,0,0,1.0,2625.0,1281.5,0,0,1,0,0.0,999.0,406.0,1,0,0,0,2.0,36.0,12.0,0,1,0,0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,b0a17a6d92b7807059fde46488badae3,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,旅館,ホテル・旅館,50,13625,6800,3,178,1,1,1,1,1,2,1,1,2,東海,三重県,三重,0,0,0,0,0,0,0,0,0,0,50.0,100.0,77.5,0,1,0,0,1.0,2625.0,1281.5,0,0,1,0,0.0,999.0,406.0,0,0,1,0,2.0,36.0,12.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,3109388c81e16b156cb5bb6c5414333e,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,宅配,宅配,55,1960,880,4,NA,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,関東,東京都,銀座・新橋・東京・上野,1,0.25,1,0.25,3,0.75,0,0,3,0.75,50.0,100.0,77.5,0,1,0,0,1.0,2625.0,1281.5,1,0,0,0,0.0,999.0,406.0,1,0,0,0,2.0,36.0,12.0,0,1,0,0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,4,1.0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,3dcb2da19b5975df3a17313dd4e05f27,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,ホテル,ホテル・旅館,69,16170,5000,5,178,1,1,1,1,1,2,1,1,2,中国,広島県,広島,0,0,0,0,0,0,0,0,0,0,50.0,100.0,77.5,0,1,0,0,1.0,2625.0,1281.5,0,0,1,0,0.0,999.0,406.0,0,0,1,0,2.0,36.0,12.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,b6123116268a9b1645e160e7abfdb496,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,ネイル・アイ,ネイル・アイ,68,17500,5500,4,90,1,1,1,1,1,1,1,1,1,関東,東京都,恵比寿・目黒・品川,0,0,0,0,3,0.75,1,0.25,3,0.75,50.0,100.0,77.5,0,1,0,0,1.0,2625.0,1281.5,0,0,1,0,0.0,999.0,406.0,0,0,1,0,2.0,36.0,12.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17f0f6675b8a3f2d9b2f2035cf9b6c57,0871d5de805bf7f26fca485d24ec65e9,1,41.0,千葉県,495,0,4,20,0,0,1,1,1,グルメ,グルメ,51,7150,3500,7,57,0,1,1,1,1,1,1,1,1,関東,神奈川県,横浜,0,0,0,0,3,0.75,0,0,0,0,50.0,100.0,77.5,0,1,0,0,1.0,2625.0,1281.5,0,0,1,0,0.0,999.0,406.0,0,0,1,0,2.0,36.0,12.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```

```
$ head -10 test_predictions_xgb.csv 
USER_ID_hash,COUPON_ID_hash,Prediction
17f0f6675b8a3f2d9b2f2035cf9b6c57,1442892055dac7335c115d50186bedd3,0.00188703
17f0f6675b8a3f2d9b2f2035cf9b6c57,e0e86297922c5799ee19881ca999b81d,0.0032071
17f0f6675b8a3f2d9b2f2035cf9b6c57,cb4c67c749dc53afd24aea31de705108,0.000529881
17f0f6675b8a3f2d9b2f2035cf9b6c57,42cc500acba3c79883cfd40adcd5ae96,0.123544
17f0f6675b8a3f2d9b2f2035cf9b6c57,b0a17a6d92b7807059fde46488badae3,0.00030684
17f0f6675b8a3f2d9b2f2035cf9b6c57,3109388c81e16b156cb5bb6c5414333e,0.0174677
17f0f6675b8a3f2d9b2f2035cf9b6c57,3dcb2da19b5975df3a17313dd4e05f27,0.00132514
17f0f6675b8a3f2d9b2f2035cf9b6c57,b6123116268a9b1645e160e7abfdb496,0.00156579
17f0f6675b8a3f2d9b2f2035cf9b6c57,0871d5de805bf7f26fca485d24ec65e9,0.00301007
```

Thank you.

**Comment by daxiongshu** [comment]
Thank you! Was the data changed by kaggle? My data is still the oldest

**Comment by SudalaiRajkumar** [comment]
Oh!! I don't think so.. May be am I using old data? Please let me know..

**Comment by daxiongshu** [comment]
Ok, don't worry, let me make a post on the forum and check my files against yours at the same time.

**Comment by SudalaiRajkumar** [comment]
Great! Thanks..

**Comment by daxiongshu** [comment]
um, the test_predictions_xgb.csv is significantly different

could you let me know the md5sum number of other files

for example
md5sum test_idvs.csv

**Comment by SudalaiRajkumar** [comment]
Am outside. I will get the md5 sum once am back home.. :)

**Comment by SudalaiRajkumar** [comment]
md5sum of the given data files are as follows:

```
9b98c97205ffb405b8598402936256e0  coupon_area_test.csv
4b9341469a84ecb209d0c48ca5b11aca  coupon_area_train.csv
8faa79f700e77c9e9b244cadc968cee4  coupon_detail_train.csv
4f81387f84a577978a934c2c7c4e912e  coupon_list_test.csv
56fb27f0f94158619001c8b1fffada93  coupon_list_train.csv
53fd38401ded5747382894883bd81b28  coupon_visit_train.csv
4486a2255a2f03a76ff3bbdaee5705a6  user_list.csv
```

md5sum of the created files are as follows:

```
737f3c9f7130c1c0e725ddba21f6157f  coupon_detail_feature.csv
221df759f2eaa76fe733949936406d68  coupon_detail_train.csv
50b926603a3bd0b4fc13b99f8efa7e63  coupon_list_feature.csv
0fade0a052e50d0cc285ab7f4dd72302  coupon_list_train.csv
ee6ee36c416d1792a223b1fc7b52f232  coupon_visit_feature.csv
2a357efa8994159271519bc012a3ad72  coupon_visit_train.csv
```

Are these files matching? I have deleted the train_idvs.csv and test_idvs.csv. I will recreate them and send the md5sum of the files

**Comment by daxiongshu** [comment]
Hi, the md5sum is the same with mine. Could you run the sub10 again and submit on your side? Thank you very much.

**Comment by daxiongshu** [comment]
Hi, is there cv code in the repo? Could you let me know the cv score of the sub10 please?

Thank you very much.

**Comment by SudalaiRajkumar** [comment]
Hi Carl, I tried creating the sub10 file and it created the same sub10 file which I submitted already. So I did not submit to check that. However it differed from the sub10 file which you have created. 

May be I have updated wrong codes?! I will check it again once.

I will also get the md5 sum of the train_idvs.csv and test_idvs.csv of sub10.

**Comment by daxiongshu** [comment]
Hey, it's ok, as long as you can reproduce it. I did use a different version of xgboost, 0.4, which could be the reason. Thank you very much.

**Comment by SudalaiRajkumar** [comment]
I don't have the cv scores of sub10. I was not sure of the evaluation metric and so I did not compute the cv scores. 

I have codes for getting the cv though. It is just that it is not in proper shape. Now that the system is fixed, I will put together the cv code and update it. Sorry for the delay. Thank you. codes only after sub10. I will send

**Comment by daxiongshu** [comment]
That's very Ok, so in your experience, is logloss or auc doing well? If I could optimize them before post processing, will it improve the final score?

**Comment by SudalaiRajkumar** [comment]
AUC was doing well so far. Yes, optimizing the AUC score before post processing will improve the final score. This is what I optimized to improve our final score since I didn't have a proper validation.

**Comment by daxiongshu** [comment]
That's great! So what is the auc score for validation of sub10? I'd like to have a general idea. Thank you.

I'm still waiting for the response of the EEG admin regarding the per subject model. Before that, I will look at coupon. : )

Best regards,

**Comment by SudalaiRajkumar** [comment]
Carl, I just checked the codes and they match with that of github. Now I will get the md5sum of train_idvs.csv and test_idvs.csv files.

**Comment by SudalaiRajkumar** [comment]
It is around 0.89 i think. My bad... I couldn't exactly recall the value. I did not look at this comp for some time now and I forgot.. That is bad of me.. :(

I have updated the "buildModel_xgb.py" code which I have used for model building in SRK/CV folder. I will run it in few mins and update you on this.

I got the md5sum for train_idvs.csv file and it is 6981f875a30be72ede510d75e1219f1e

I am generating test_idvs.csv file now

**Comment by SudalaiRajkumar** [comment]
Though I 5-fold cross val is present in the validation script I uploaded, I just looked at the first val split score during my model building (just to save time). Val score is 0.8937 for this fold.

md5sum of the test_idvs.csv is as follows.
c382bae22b2d88d6b870e2753147cf4f  - test_idvs.csv

I will try and get the proper cv computation codes ready by either today or tomorrow

**Comment by daxiongshu** [comment]
Thank you very much. I tested. All files are identical so it must be the different version of xgb.

Could you please share the test_predictions_xgb.csv for sub10.csv? So I can ensemble upon it.

Thank you again. : )

**Comment by SudalaiRajkumar** [comment]
Carl, I have the shared the test_predictions_xgb file for sub10 with you through google drive. Please let me know if you are able to access it.

**Comment by daxiongshu** [comment]
Thank you very much. I got it and I improved a little bit when averaging it with the ftrl model. I uploaded the ftrl code in your folder since it reuses a lot of your code. : )

**Comment by SudalaiRajkumar** [comment]
Great work Carl. Thank you very much. Good to see some improvement. 

We could add variables based on location.CSV and visit.CSV files. I will do those things once our grasp competition is over. I am planning to take part only on this competition after grasp competition.

**Comment by SudalaiRajkumar** [comment]
Check this post by Jose
https://www.kaggle.com/c/coupon-purchase-prediction/forums/t/15971/map-10-inestability/89565#post89565

This is what exactly I came across as well and so I thought I made a mistake. Now that he has confirmed that the score varies across different weeks, we can safely assume that our cv is working correct. :) By the way, our score for the previous week is around 0.014 for sub10 I think. I will clean and post the CV codes to github soon :) Thank you..

**Comment by daxiongshu** [comment]
Yeah, I see. So the last week is the golden validation set for this one, is it?

**Comment by SudalaiRajkumar** [comment]
Nope. Actually last week gives a higher value that the actual test week. Last weeks value is 0.014 and the test week is 0.0104. There is a change in map@10 values across weeks. But I presume if we improve the map@10 of last week, it will improve the results of test week as well. 

As mentioned by Jules in the same post, it may be because of the change in number of new coupons.

**Comment by daxiongshu** [comment]
Ok, I see. Thank you very much. By the way, in the post processing, you select the top 10 coupons for each user, did you try other numbers? 

Best regards,

**Comment by SudalaiRajkumar** [comment]
I tried two once and it gave bad results than 10. I think making ten
predictions does not hurt according to the metric.. Probably we can try and
confirm it once..

**Comment by daxiongshu** [comment]
Sorry, I used out all the submissions of today. I tried a top 15 threshold and it scores the same with the top 10. I will not submit blindly from now on and always cv first : )

**Comment by SudalaiRajkumar** [comment]
No problem. It is fine to make more submissions and check now itself rather that doing at the last :) Also I don't have anything concrete to make a submission as well.

Please feel free to use the submissions and test the LB :) I will let you know if I need a submission.

New guy at the top. Competition is heating up :)

**Comment by daxiongshu** [comment]
Yeah, I am 99% sure that nagadomi is using neural network and that is what I am going to try for the next step :P

**Comment by SudalaiRajkumar** [comment]
oh!! How can you be so confident?? I am just curious

**Comment by daxiongshu** [comment]
Hah, it is just a guess based on my impression in the past contests. nagadomi always shows at the top if deep nn does well, see his github repo, https://github.com/nagadomi/kaggle-ndsb.

Or a better evidence is his posts on the forum, https://www.kaggle.com/nagadomi/forum
You will see a lot of buzz word, aka, 'neural network'. : )

**Comment by SudalaiRajkumar** [comment]
U r awesome!! Great inference :) So we can be sure that neural nets perform good on this dataset :)

Also just noted that he is from Japan !

**Comment by SudalaiRajkumar** [comment]
We have an in-house neon expert now and so we don't have to worry about neural nets now ;)

I need to get a GPU and to upgrade my system soon. Getting tough with the increasing size in dataset and also not able to run neural nets.

**Comment by daxiongshu** [comment]
Yeah, I also have a GPU installed. It will a great chance to learn deep learning. : )

**Comment by SudalaiRajkumar** [comment]
Yes :) You are already an expert at deep learning right?

**Comment by daxiongshu** [comment]
No, I am just a beginner. I am recently studying this tutorial http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/ which is really well written but it is for CNN, which I don't think will apply here. But I believe a regular nn will have a good chance. I will try this one first, https://github.com/diefimov/otto_2015/tree/master/otto-py, they have some nice nn model for the otto challenge and your previous nn model for the CrowdFlower challenge.

**Comment by SudalaiRajkumar** [comment]
I am a beginner in nn as well. I have tried pylearn2 in the past. Recently I started trying out lasagne and keras. Definitely I think Efimov's code will help. 

I started liking Keras out of the three for its sklearn type implementation and easy to use. I haven't used the full potential of lasagne yet and so I may be wrong. Please let me know your views once you start using NNs. I will start learning once I get a GPU and from your codes for this competition :)

**Comment by SudalaiRajkumar** [comment]
Carl, I have updated the cv codes which is used to compute the map@10 metric for the val sample in github. Please have a look at it when free. I think it is a little messy. I will put it in proper shape soon.
